export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAIL = "GET_ALL_MOVIES_FAIL";
export const GET_ALL_MOVIES_RESET = "GET_ALL_MOVIES_RESET";

export const GET_SELECTED_MOVIES_REQUEST = "GET_SELECTED_MOVIES_REQUEST";
export const GET_SELECTED_MOVIES_SUCCESS = "GET_SELECTED_MOVIES_SUCCESS";
export const GET_SELECTED_MOVIES_FAIL = "GET_SELECTED_MOVIES_FAIL";
export const GET_SELECTED_MOVIES_RESET = "GET_SELECTED_MOVIES_RESET";

export const GET_RANDOM_MOVIES_REQUEST = "GET_RANDOM_MOVIES_REQUEST";
export const GET_RANDOM_MOVIES_SUCCESS = "GET_RANDOM_MOVIES_SUCCESS";
export const GET_RANDOM_MOVIES_FAIL = "GET_RANDOM_MOVIES_FAIL";
export const GET_RANDOM_MOVIES_RESET = "GET_RANDOM_MOVIES_RESET";

export const GET_SINGLE_MOVIE_REQUEST = "GET_SINGLE_MOVIE_REQUEST";
export const GET_SINGLE_MOVIE_SUCCESS = "GET_SINGLE_MOVIE_SUCCESS";
export const GET_SINGLE_MOVIE_FAIL = "GET_SINGLE_MOVIE_FAIL";
export const GET_SINGLE_MOVIE_RESET = "GET_SINGLE_MOVIE_RESET";

export const GET_TOP_MOVIES_REQUEST = "GET_TOP_MOVIES_REQUEST";
export const GET_TOP_MOVIES_SUCCESS = "GET_TOP_MOVIES_SUCCESS";
export const GET_TOP_MOVIES_FAIL = "GET_TOP_MOVIES_FAIL";
export const GET_TOP_MOVIES_RESET = "GET_TOP_MOVIES_RESET";

export const SEND_REVIEW_REQUEST = "SEND_REVIEW_REQUEST";
export const SEND_REVIEW_SUCCESS = "SEND_REVIEW_SUCCESS";
export const SEND_REVIEW_FAIL = "SEND_REVIEW_FAIL";
export const SEND_REVIEW_RESET = "SEND_REVIEW_RESET";

export const LIKE_MOVIE_REQUEST = "LIKE_MOVIE_REQUEST";
export const LIKE_MOVIE_SUCCESS = "LIKE_MOVIE_SUCCESS";
export const LIKE_MOVIE_FAIL = "LIKE_MOVIE_FAIL";
export const LIKE_MOVIE_RESET = "LIKE_MOVIE_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";

export const DELETE_ALL_MOVIES_REQUEST = "DELETE_ALL_MOVIES_REQUEST";
export const DELETE_ALL_MOVIES_SUCCESS = "DELETE_ALL_MOVIES_SUCCESS";
export const DELETE_ALL_MOVIES_FAIL = "DELETE_ALL_MOVIES_FAIL";
export const DELETE_ALL_MOVIES_RESET = "DELETE_ALL_MOVIES_RESET";

export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL";
export const CREATE_MOVIE_RESET = "CREATE_MOVIE_RESET";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";

export const GET_MOVIES_BY_YEAR_REQUEST = "GET_MOVIES_BY_YEAR_REQUEST";
export const GET_MOVIES_BY_YEAR_SUCCESS = "GET_MOVIES_BY_YEAR_SUCCESS";
export const GET_MOVIES_BY_YEAR_FAIL = "GET_MOVIES_BY_YEAR_FAIL";
export const GET_MOVIES_BY_YEAR_RESET = "GET_MOVIES_BY_YEAR_RESET";

export const ADD_CAST = "ADD_CAST";
export const EDIT_CAST = "EDIT_CAST";
export const DELETE_CAST = "DELETE_CAST";
export const RESET_CAST = "RESET_CAST";
