export const USER_ADD_NEW_VIDEO_REQUEST = "USER_ADD_NEW_VIDEO_REQUEST";
export const USER_ADD_NEW_VIDEO_SUCCESS = "USER_ADD_NEW_VIDEO_SUCCESS";
export const USER_ADD_NEW_VIDEO_FAIL = "USER_ADD_NEW_VIDEO_FAIL";
export const USER_ADD_NEW_VIDEO_RESET = "USER_ADD_NEW_VIDEO_RESET";

export const USER_GET_PRIVATE_VIDEOS_REQUEST =
  "USER_GET_PRIVATE_VIDEOS_REQUEST";
export const USER_GET_PRIVATE_VIDEOS_SUCCESS =
  "USER_GET_PRIVATE_VIDEOS_SUCCESS";
export const USER_GET_PRIVATE_VIDEOS_FAIL = "USER_GET_PRIVATE_VIDEOS_FAIL";
export const USER_GET_PRIVATE_VIDEOS_RESET = "USER_GET_PRIVATE_VIDEOS_RESET";

export const USER_GET_ALL_VIDEO_REQUEST = "USER_GET_ALL_VIDEO_REQUEST";
export const USER_GET_ALL_VIDEO_SUCCESS = "USER_GET_ALL_VIDEO_SUCCESS";
export const USER_GET_ALL_VIDEO_FAIL = "USER_GET_ALL_VIDEO_FAIL";
export const USER_GET_ALL_VIDEO_RESET = "USER_GET_ALL_VIDEO_RESET";

export const USER_GET_VIDEO_BY_ID_REQUEST = "USER_GET_VIDEO_BY_ID_REQUEST";
export const USER_GET_VIDEO_BY_ID_SUCCESS = "USER_GET_VIDEO_BY_ID_SUCCESS";
export const USER_GET_VIDEO_BY_ID_FAIL = "USER_GET_VIDEO_BY_ID_FAIL";
export const USER_GET_VIDEO_BY_ID_RESET = "USER_GET_VIDEO_BY_ID_RESET";

export const USER_UPDATE_VIDEO_REQUEST = "USER_UPDATE_VIDEO_REQUEST";
export const USER_UPDATE_VIDEO_SUCCESS = "USER_UPDATE_VIDEO_SUCCESS";
export const USER_UPDATE_VIDEO_FAIL = "USER_UPDATE_VIDEO_FAIL";
export const USER_UPDATE_VIDEO_RESET = "USER_UPDATE_VIDEO_RESET";

export const USER_DELETE_VIDEO_REQUEST = "USER_DELETE_VIDEO_REQUEST";
export const USER_DELETE_VIDEO_SUCCESS = "USER_DELETE_VIDEO_SUCCESS";
export const USER_DELETE_VIDEO_FAIL = "USER_DELETE_VIDEO_FAIL";
export const USER_DELETE_VIDEO_RESET = "USER_DELETE_VIDEO_RESET";

export const USER_DELETE_ALL_VIDEOS_REQUEST = "USER_DELETE_ALL_VIDEOS_REQUEST";
export const USER_DELETE_ALL_VIDEOS_SUCCESS = "USER_DELETE_ALL_VIDEOS_SUCCESS";
export const USER_DELETE_ALL_VIDEOS_FAIL = "USER_DELETE_ALL_VIDEOS_FAIL";
export const USER_DELETE_ALL_VIDEOS_RESET = "USER_DELETE_ALL_VIDEOS_RESET";

//==================== MUSIC CONSTANTS ====================

export const USER_GET_ALL_MUSIC_REQUEST = "USER_GET_ALL_MUSIC_REQUEST";
export const USER_GET_ALL_MUSIC_SUCCESS = "USER_GET_ALL_MUSIC_SUCCESS";
export const USER_GET_ALL_MUSIC_FAIL = "USER_GET_ALL_MUSIC_FAIL";
export const USER_GET_ALL_MUSIC_RESET = "USER_GET_ALL_MUSIC_RESET";

export const USER_GET_ALL_PRIVATE_MUSIC_REQUEST =
  "USER_GET_ALL_PRIVATE_MUSIC_REQUEST";
export const USER_GET_ALL_PRIVATE_MUSIC_SUCCESS =
  "USER_GET_ALL_PRIVATE_MUSIC_SUCCESS";
export const USER_GET_ALL_PRIVATE_MUSIC_FAIL =
  "USER_GET_ALL_PRIVATE_MUSIC_FAIL";
export const USER_GET_ALL_PRIVATE_MUSIC_RESET =
  "USER_GET_ALL_PRIVATE_MUSIC_RESET";

export const USER_DELETE_PRIVATE_MUSIC_REQUEST =
  "USER_DELETE_PRIVATE_MUSIC_REQUEST";
export const USER_DELETE_PRIVATE_MUSIC_SUCCESS =
  "USER_DELETE_PRIVATE_MUSIC_SUCCESS";
export const USER_DELETE_PRIVATE_MUSIC_FAIL = "USER_DELETE_PRIVATE_MUSIC_FAIL";
export const USER_DELETE_PRIVATE_MUSIC_RESET =
  "USER_DELETE_PRIVATE_MUSIC_RESET";

// ==================== DOCUMENTS CONSTANTS ====================

export const USER_GET_ALL_DOCUMENTS_REQUEST = "USER_GET_ALL_DOCUMENTS_REQUEST";
export const USER_GET_ALL_DOCUMENTS_SUCCESS = "USER_GET_ALL_DOCUMENTS_SUCCESS";
export const USER_GET_ALL_DOCUMENTS_FAIL = "USER_GET_ALL_DOCUMENTS_FAIL";
export const USER_GET_ALL_DOCUMENTS_RESET = "USER_GET_ALL_DOCUMENTS_RESET";

export const USER_GET_ALL_PRIVATE_DOCUMENT_REQUEST =
  "USER_GET_ALL_PRIVATE_DOCUMENT_REQUEST";
export const USER_GET_ALL_PRIVATE_DOCUMENT_SUCCESS =
  "USER_GET_ALL_PRIVATE_DOCUMENT_SUCCESS";
export const USER_GET_ALL_PRIVATE_DOCUMENT_FAIL =
  "USER_GET_ALL_PRIVATE_DOCUMENT_FAIL";
export const USER_GET_ALL_PRIVATE_DOCUMENT_RESET =
  "USER_GET_ALL_PRIVATE_DOCUMENT_RESET";

export const USER_DELETE_PRIVATE_DOCUMENTS_REQUEST =
  "USER_DELETE_PRIVATE_DOCUMENTS_REQUEST";
export const USER_DELETE_PRIVATE_DOCUMENTS_SUCCESS =
  "USER_DELETE_PRIVATE_DOCUMENTS_SUCCESS";
export const USER_DELETE_PRIVATE_DOCUMENTS_FAIL =
  "USER_DELETE_PRIVATE_DOCUMENTS_FAIL";
export const USER_DELETE_PRIVATE_DOCUMENTS_RESET =
  "USER_DELETE_PRIVATE_DOCUMENTS_RESET";

// ==================== PHOTO CONSTANTS ====================

export const USER_GET_ALL_PHOTO_REQUEST = "USER_GET_ALL_PHOTO_REQUEST";
export const USER_GET_ALL_PHOTO_SUCCESS = "USER_GET_ALL_PHOTO_SUCCESS";
export const USER_GET_ALL_PHOTO_FAIL = "USER_GET_ALL_PHOTO_FAIL";
export const USER_GET_ALL_PHOTO_RESET = "USER_GET_ALL_PHOTO_RESET";

export const USER_GET_ALL_PRIVATE_PHOTO_REQUEST =
  "USER_GET_ALL_PRIVATE_PHOTO_REQUEST";
export const USER_GET_ALL_PRIVATE_PHOTO_SUCCESS =
  "USER_GET_ALL_PRIVATE_PHOTO_SUCCESS";
export const USER_GET_ALL_PRIVATE_PHOTO_FAIL =
  "USER_GET_ALL_PRIVATE_PHOTO_FAIL";
export const USER_GET_ALL_PRIVATE_PHOTO_RESET =
  "USER_GET_ALL_PRIVATE_PHOTO_RESET";

export const USER_DELETE_PRIVATE_PHOTO_REQUEST =
  "USER_DELETE_PRIVATE_PHOTO_REQUEST";
export const USER_DELETE_PRIVATE_PHOTO_SUCCESS =
  "USER_DELETE_PRIVATE_PHOTO_SUCCESS";
export const USER_DELETE_PRIVATE_PHOTO_FAIL = "USER_DELETE_PRIVATE_PHOTO_FAIL";
export const USER_DELETE_PRIVATE_PHOTO_RESET =
  "USER_DELETE_PRIVATE_PHOTO_RESET";
