import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "aos";
import "aos/dist/aos.css";
import Navbar from "@/layouts/navbar/Navbar";
import Footer from "@/layouts/footer/Footer";
import ScrollOnTop from "@/components/ScrollOnTop";
import MobileFooter from "@/layouts/footer/MobileFooter";
import ToastContainer from "@/components/notifications/ToastContainer";
import dynamic from "next/dynamic";
import DrawerContext from "@/context/DrawerContext";
import { Metadata } from "@/Types";
import AppProvider from "@/redux/Provider";

const NoSSR = dynamic(() => import("@/components/ScrollOnTop"), { ssr: false });

const metadata: Metadata = {
  title: "VidStream-Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                var methods = ['log', 'debug', 'warn', 'info', 'error'];
                for (var i = 0; i < methods.length; i++) {
                  console[methods[i]] = function() {};
                }
              })();
            `,
          }}
        /> */}
      </head>
      <body>
        <div className="bg-main text-white">
          <AppProvider>
            <NoSSR>
              <ToastContainer />
              <DrawerContext>
                <ScrollOnTop>
                  <Navbar />
                  {children}
                  <Footer />
                  <MobileFooter />
                </ScrollOnTop>
              </DrawerContext>
            </NoSSR>
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
